### ISSUE TITLE
Bug with Markdown url syntax

### ISSUE THREAD

**Issue by romulomourao** [romulomourao/awesome-courses#28]
Does anyone know how to solve this problem? 
The link **thenewboston - Python 3.4 Programming Tutorials** on Python section is broken because it finishes with underscore

**Comment by jaydp17** [comment]
Try removing the space between `] (`
It works without space

**Comment by jaydp17** [comment]
Here's the pull request https://github.com/romulomourao/awesome-courses/pull/29

**Comment by romulomourao** [comment]
#29
