### ISSUE TITLE
Add more programming languages 

### ISSUE THREAD

**Issue by romulomourao** [romulomourao/awesome-courses#7]
Help me to add more programming languages in Youtube Playlists section
Remember: *Alphabetical order*

**Comment by Jpfonseca** [comment]
Hi, I think you should consider to have a language tag . There are neat Programming videos on Youtube made by non-English speakers

**Comment by sagarkar10** [comment]
I want to add resources for python and c/c++. Can you assign me the task?

**Comment by romulomourao** [comment]
Great, @Jpfonseca. Could you do that? 

@sagarkar10 no problem, man.

**Comment by danmcatee** [comment]
I would add some more JavaScript, HTML and CSS content

**Comment by sagarkar10** [comment]
Added a PR please review

**Comment by TheFaR8** [comment]
I want to add websites (and maybe a few resources). Can you please assign me to the task?
